# Cuneiform Geography

Each cuneiform tablet has a provenience, or place of discovery. Sometimes this information is lost due to illicit digging and the lack of documentation, but when it is known, this data has been published in the open source databases of cuneiform texts, most notably: [CDLI](https://cdli.mpiwg-berlin.mpg.de/), [ORACC](oracc.museum.upenn.edu), and [BDTNS](http://bdtns.filol.csic.es/).
In 2021 a team of specialists published a dataset of proveniences for the cuneiform sources in Zenodo, entitled [Cuneiform Inscriptions Geographical Site Index](https://zenodo.org/record/5642899#.YxeO1uzMLy9). Their data curation extended beyond that of the existing databases, and has become the dataset of record for geographical metadata for these artifacts, and has since been included in the CDLI.

The goal of this initial notebook is (1) to access this dataset using reproducible methods, and compare previous and current versions, and lastly (2) to prepare this data for Linked Open Data (LOD) triple statements in the [FactGrid Cuneiform Project](https://database.factgrid.de/wiki/FactGrid:Cuneiform_Project).

------------

**License:**

Attribution 4.0 International [CC-BY](https://github.com/santisoler/cc-licenses/blob/main/LICENSE-CC-BY)

----------
> __Citation references:__
* License: [CC-BY 4.0](https://github.com/santisoler/cc-licenses/blob/main/LICENSE-CC-BY)
* Title: Cuneiform Geography
* Date: Spring 2023
* Authors:
  1. Tina Chen (czz129@berkeley.edu). UC Berkeley Data Science major (2024)
  2. Dr. Adam Anderson (adamganderson@gmail.com). UC Berkeley Data Science Discovery Partner, FactGrid Cuneiform project director.

* Project: [FactGrid Cuneiform](https://database.factgrid.de/wiki/FactGrid:Cuneiform_Project)
* Program: [UC Berkeley Data Science Discovery](https://data.berkeley.edu/project/factgrid-cuneiform)

In [ ]:
!pip3 install geojson
!pip3 install shapely.constructive
!pip install --upgrade geopandas
import pandas as pd
import numpy as np
import csv
import plotly.express as px
import geopandas as gpd
import json
import requests
%matplotlib inline
from shapely.geometry import Point
from geopandas import datasets, GeoDataFrame, read_file

Collecting geojson
  Downloading geojson-3.0.1-py3-none-any.whl (15 kB)
Installing collected packages: geojson
Successfully installed geojson-3.0.1
ERROR: Could not find a version that satisfies the requirement shapely.constructive (from versions: none)
ERROR: No matching distribution found for shapely.constructive
Requirement already satisfied: geopandas in /usr/local/lib/python3.10/dist-packages (0.13.2)
Requirement already satisfied: fiona>=1.8.19 in /usr/local/lib/python3.10/dist-packages (from geopandas) (1.9.4.post1)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from geopandas) (23.1)
Requirement already satisfied: pandas>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from geopandas) (1.5.3)
Requirement already satisfied: pyproj>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from geopandas) (3.6.0)
Requirement already satisfied: shapely>=1.7.1 in /usr/local/lib/python3.10/dist-packages (from geopandas) (2.0.1)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (23.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (2023.5.7)
Requirement already satisfied: click~=8.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (8.1.4)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (1.1.1)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (0.7.2)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0->geopandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0->geopandas) (1.22.4)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
workdir = '/content/drive/MyDrive/Sumerian Network' # for Tina

Mounted at /content/drive

##1 Published Data for Cuneiform Tablet Proveniences

1.1 The first step is to import the CIGS dataset (geojson) [Rattenborg, Rune, Johansson, Carolin, Nett, Seraina, Smidt, Gustav Ryberg, & Andersson, Jakob. (2021). Cuneiform Inscriptions Geographical Site Index (CIGS) (1.4) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.5642899](https://zenodo.org/record/5642899#.YxeO1uzMLy9)

1.2 Then we will compare this with the updated version of the CIGS dataset (CSV) [Rattenborg, Rune, Johansson, Carolin, Melin-Kronsell, Nils, Nett, Seraina, Smidt, Gustav Ryberg, & Andersson, Jakob. (2023). Cuneiform Inscriptions Geographical Site Index (CIGS) (v1.6). Zenodo. https://doi.org/10.5281/zenodo.8126955](https://zenodo.org/record/8126955)

In [ ]:
CIGS_old = gpd.read_file('/content/drive/MyDrive/FactGrid Cuneiform (AWCA)/geography/CIGS_v1_4_20211101.geojson')
CIGS
CIGS = gpd.read_file('/content/drive/MyDrive/FactGrid Cuneiform (AWCA)/geography/CIGS_v1_6_20230613.csv')
CIGS

,site_id,cdli_provenience_id,accuracy,anc_name,transc_name,ara_name,arm_name,fas_name,geo_name,gre_name,...,wik_ara,wik_fas,wik_gre,wik_heb,wik_tr,rla_url,wikidata_url,lon_wgs1984,lat_wgs1984,geometry
0,ADA,0,2,,Adalar,,,,,,...,,,,,,,,42.5142,39.1240,None
1,ADB,252,3,Adab,Bismāyā,بسمايا,,,,,...,https://ar.wikipedia.org/wiki/أداب_(مدينة),,,,,,https://wikidata.org/wiki/Q346445,45.6233,31.9509,None
2,ADH,0,3,,Tall Abū al-Dhahab,تل أبو الذهب,,,,,...,,,,,,,,46.6926,30.7382,None
3,ADI,0,1,,Adilcevaz,,,,,,...,,,,,https://tr.wikipedia.org/wiki/Adilcevaz,,https://wikidata.org/wiki/Q357251,42.7291,38.8014,None
4,AFA,0,3,,Tulūl al-Fāj,تلول الفاج,,,,,...,,,,,,,,45.0956,32.5741,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
592,ZLB,58,1,,Zālūl Āb,زالوآب,,,,,...,,https://fa.wikipedia.org/wiki/زالوآب_(روانسر),,,,,,46.5799,34.6309,None
593,ZOH,116,1,,Sar-i Pol-i Zohāb,,,سر پل زهاب,,,...,,,,,,,,45.8692,34.4633,None
594,ZTP,244,3,Tushhan,Ziyaret Tepe,,,,,,...,,,,,https://tr.wikipedia.org/wiki/Ziyaret_Tepe_Höyüğü,,https://wikidata.org/wiki/Q4819172,40.7929,37.7936,None
595,ZVA,0,1,,Zvartʻnotsʻ,,Զվարթնոց,,,,...,,https://fa.wikipedia.org/wiki/سنگ%E2%80%8Cنگار...,,,,,https://wikidata.org/wiki/Q505175,44.3366,40.1596,None
596,ZWY,271,1,,Zawiyah,زوية,,,,,...,,,,,,,,42.1725,34.2925,None

In [ ]:
CIGS.iloc[407]

site_id                                                        QIT
cdli_provenience_id                                              0
accuracy                                                         3
anc_name
transc_name                                          Tall al-Qiṭar
ara_name                                                 تل القطار
arm_name
fas_name
geo_name
gre_name
heb_name
rus_name
legacy_name
pleiades_url
osm_url                https://www.openstreetmap.org/way/766039147
geonames_url                         https://www.geonames.org/9082
wik_en
wik_ara
wik_fas
wik_gre
wik_heb
wik_tr
rla_url
wikidata_url
lon_wgs1984                                                38.1803
lat_wgs1984                                                36.3837
geometry                                                      None
Name: 407, dtype: object

In [ ]:
CIGS.columns

Index(['site_id', 'cdli_provenience_id', 'accuracy', 'anc_name', 'transc_name',
       'ara_name', 'arm_name', 'fas_name', 'geo_name', 'gre_name', 'heb_name',
       'rus_name', 'legacy_name', 'pleiades_url', 'osm_url', 'geonames_url',
       'wik_en', 'wik_ara', 'wik_fas', 'wik_gre', 'wik_heb', 'wik_tr',
       'rla_url', 'wikidata_url', 'lon_wgs1984', 'lat_wgs1984', 'geometry'],
      dtype='object')

In [ ]:
# CIGS["pleiades_id"]

##2 LOD format for FactGrid
In order for the CIGS dataset to be imported into FactGrid, we need to add a few things for proper formatting in Linked Open Data (LOD), which include:
1. Property IDs for the corresponding items in the header field
2. Quotation marks around labels for each item
3. Additional formatting tags for special language fields, etc.

FactGrid uses Quickstatements for importing in CSV format. The formatting rules for Quickstatements are documented for Wikidata (https://www.wikidata.org/wiki/Help:QuickStatements). There is also a video description [here](https://blog.factgrid.de/archives/811).

In [ ]:
path = '/content/drive/MyDrive/FactGrid Cuneiform (AWCA)/geography/LOD Tablet Dictionary - CIGS_FG.csv'
CIGS_FG = pd.read_csv(path, header=[0])
CIGS_FG

,Double record?,qid,Sarwiki,P418,P34,Unnamed: 5,Unnamed: 6,Senwiki,P671,P34.1,...,wik_fas,wik_gre,wik_heb,wik_en.1,lan,qid.2,"qid,Len,Lfr,Lde,Den,P2,P2,P131,P131,P48,P670,qal18",place,link,placeLabel
0,NaN,Q389858,"""سيبار_أمنانوم""","""6927582""",NaN,NaN,NaN,"""Sippar-Amnanum ""","""392373882""","ar:""تل الدير""",...,NaN,NaN,NaN,https://en.wikipedia.org/wiki/Sippar-Amnanum,NaN,NaN,",""Tall al-Daiyr"",""Tall al-Daiyr"",""Tall al-Daiy...",Q390078,Q756957,Hasankeyf
1,NaN,Q389791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ar:""أم الجير""",...,NaN,NaN,NaN,NaN,NaN,NaN,",""Umm al-Jīr"",""Umm al-Jīr"",""Umm al-Jīr"",""ancie...",NaN,NaN,NaN
2,NaN,Q389689,NaN,"""7108432""","fa:""تپه حصار""",NaN,NaN,"""Tepe Hissar ""","""942329""",NaN,...,https://fa.wikipedia.org/wiki/تپه%E2%80%8Cحصار,NaN,NaN,https://en.wikipedia.org/wiki/Tepe_Hissar,NaN,NaN,",""Tapah Ḥiṣār"",""Tapah Ḥiṣār"",""Tapah Ḥiṣār"",""an...",NaN,NaN,NaN
3,NaN,Q390037,NaN,NaN,NaN,Strwiki,"""Maşat Höyük""","""Maşat Höyük ""","""133411593""",NaN,...,NaN,NaN,NaN,https://en.wikipedia.org/wiki/Maşat_Höyük,NaN,NaN,",""Maşat Höyük"",""Maşat Höyük"",""Maşat Höyük"",""an...",Q389991,Q82070,Ṣūr
4,NaN,Q389935,NaN,NaN,NaN,NaN,NaN,NaN,"""249999668""","ar:""تل محمد""",...,NaN,NaN,NaN,NaN,NaN,NaN,",""Tall Muḥamad"",""Tall Muḥamad"",""Tall Muḥamad"",...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576,NaN,Q390166,NaN,"""6268312""",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,",""Новый Кумак"",""Новый Кумак"",""Новый Кумак"",""an...",NaN,NaN,NaN
577,NaN,Q390170,NaN,NaN,NaN,NaN,NaN,P671,"""804216207""",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,",""Acemhöyük"",""Acemhöyük"",""Acemhöyük"",""ancient ...",NaN,NaN,NaN
578,NaN,Q389671,NaN,"""281184""",NaN,NaN,NaN,P671,"""687928""","ar:""القدس""",...,NaN,NaN,NaN,NaN,NaN,NaN,",""Yrṿshlym"",""Yrṿshlym"",""Yrṿshlym"",""ancient loc...",NaN,NaN,NaN
579,NaN,Q389718,NaN,NaN,"fa:""سقندل""",NaN,NaN,P671,"""884203""",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,",""Saqandal"",""Saqandal"",""Saqandal"",""ancient loc...",NaN,NaN,NaN
580,NaN,Q389811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ar:""الرجيبة""",...,NaN,NaN,NaN,NaN,NaN,NaN,",""Al-Rajībah"",""Al-Rajībah"",""Al-Rajībah"",""ancie...",NaN,NaN,NaN

Changed the columns without quotation mark

In [ ]:
# CIGS_FG_without_quote = CIGS_FG.copy()
# for i, col in enumerate(CIGS_FG.columns):
#     CIGS_FG.iloc[:, i] = CIGS_FG.iloc[:, i].replace('"', '')
# CIGS_FG

In [ ]:
CIGS_FG_without_quote = pd.read_csv("/content/drive/MyDrive/FactGrid Cuneiform (AWCA)/geography/CIGS_FG_without_quote.csv" )
CIGS_FG_without_quote

,Unnamed: 0,Double record?,qid,Sarwiki,P418,P34,Unnamed: 5,Unnamed: 6,Senwiki,P671,...,wik_fas,wik_gre,wik_heb,wik_en.1,lan,qid.2,"qid,Len,Lfr,Lde,Den,P2,P2,P131,P131,P48,P670,qal18",place,link,placeLabel
0,0,NaN,Q389858,سيبار_أمنانوم,6927582.0,NaN,NaN,NaN,Sippar-Amnanum,392373882.0,...,NaN,NaN,NaN,https://en.wikipedia.org/wiki/Sippar-Amnanum,NaN,NaN,",""Tall al-Daiyr"",""Tall al-Daiyr"",""Tall al-Daiy...",Q390078,Q756957,Hasankeyf
1,1,NaN,Q389791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,",""Umm al-Jīr"",""Umm al-Jīr"",""Umm al-Jīr"",""ancie...",NaN,NaN,NaN
2,2,NaN,Q389689,NaN,7108432.0,fa:تپه حصار,NaN,NaN,Tepe Hissar,942329.0,...,https://fa.wikipedia.org/wiki/تپه%E2%80%8Cحصار,NaN,NaN,https://en.wikipedia.org/wiki/Tepe_Hissar,NaN,NaN,",""Tapah Ḥiṣār"",""Tapah Ḥiṣār"",""Tapah Ḥiṣār"",""an...",NaN,NaN,NaN
3,3,NaN,Q390037,NaN,NaN,NaN,Strwiki,Maşat Höyük,Maşat Höyük,133411593.0,...,NaN,NaN,NaN,https://en.wikipedia.org/wiki/Maşat_Höyük,NaN,NaN,",""Maşat Höyük"",""Maşat Höyük"",""Maşat Höyük"",""an...",Q389991,Q82070,Ṣūr
4,4,NaN,Q389935,NaN,NaN,NaN,NaN,NaN,NaN,249999668.0,...,NaN,NaN,NaN,NaN,NaN,NaN,",""Tall Muḥamad"",""Tall Muḥamad"",""Tall Muḥamad"",...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576,576,NaN,Q390166,NaN,6268312.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,",""Новый Кумак"",""Новый Кумак"",""Новый Кумак"",""an...",NaN,NaN,NaN
577,577,NaN,Q390170,NaN,NaN,NaN,NaN,NaN,P671,804216207.0,...,NaN,NaN,NaN,NaN,NaN,NaN,",""Acemhöyük"",""Acemhöyük"",""Acemhöyük"",""ancient ...",NaN,NaN,NaN
578,578,NaN,Q389671,NaN,281184.0,NaN,NaN,NaN,P671,687928.0,...,NaN,NaN,NaN,NaN,NaN,NaN,",""Yrṿshlym"",""Yrṿshlym"",""Yrṿshlym"",""ancient loc...",NaN,NaN,NaN
579,579,NaN,Q389718,NaN,NaN,fa:سقندل,NaN,NaN,P671,884203.0,...,NaN,NaN,NaN,NaN,NaN,NaN,",""Saqandal"",""Saqandal"",""Saqandal"",""ancient loc...",NaN,NaN,NaN
580,580,NaN,Q389811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,",""Al-Rajībah"",""Al-Rajībah"",""Al-Rajībah"",""ancie...",NaN,NaN,NaN

In [ ]:
CIGS_FG_without_quote["Len"]

0      Tall al-Daiyr
1         Umm al-Jīr
2        Tapah Ḥiṣār
3        Maşat Höyük
4       Tall Muḥamad
           ...
576      Новый Кумак
577        Acemhöyük
578         Yrṿshlym
579         Saqandal
580       Al-Rajībah
Name: Len, Length: 581, dtype: object

In [ ]:
CIGS_FG_without_quote.columns

Index(['Unnamed: 0', 'Double record?', 'qid', 'Sarwiki', 'P418', 'P34',
       'Unnamed: 5', 'Unnamed: 6', 'Senwiki', 'P671', 'P34.1', 'Wikidata_qid',
       'Wikidata2', 'Len', 'Den', 'P2', 'P2.1', 'P131', 'P131.1',
       'lat_lon_P48', 'P670', 'qal18', 'wik_en', 'sv.wiki', 'wik_tr',
       'Description', 'anc_name', 'lat_wgs1984', 'lon_wgs1984', 'accuracy',
       'qid.1', 'cdli_legacy_"Len"', 'cdli_provenience_id_P694',
       'transciption_name', 'language', 'tr_name', 'ara_name', 'arm_name',
       'fas_name', 'geo_name', 'gre_name', 'heb_name', 'rus_name',
       'pleiades_id_P671', 'osm_id', 'osm_type', 'site_id', 'geonames_id',
       'Unnamed: 47', 'wik_ara', 'wik_fas', 'wik_gre', 'wik_heb', 'wik_en.1',
       'lan', 'qid.2', 'qid,Len,Lfr,Lde,Den,P2,P2,P131,P131,P48,P670,qal18',
       'place', 'link', 'placeLabel'],
      dtype='object')

Next we merge the two data tables, in order to see which fields have been added, and which still need to be added into FactGrid. Some of the fields which were not yet added may require that we first make the Property for the items in FactGrid before we can import the data directly.

In [ ]:
CIGS_MERGE = CIGS_FG_without_quote.merge(CIGS, how = 'right', left_on = 'transciption_name', right_on = "transc_name",indicator= True)
CIGS_MERGE.columns

Index(['Unnamed: 0', 'Double record?', 'qid', 'Sarwiki', 'P418', 'P34',
       'Unnamed: 5', 'Unnamed: 6', 'Senwiki', 'P671', 'P34.1', 'Wikidata_qid',
       'Wikidata2', 'Len', 'Den', 'P2', 'P2.1', 'P131', 'P131.1',
       'lat_lon_P48', 'P670', 'qal18', 'wik_en_x', 'sv.wiki', 'wik_tr_x',
       'Description', 'anc_name_x', 'lat_wgs1984_x', 'lon_wgs1984_x',
       'accuracy_x', 'qid.1', 'cdli_legacy_"Len"', 'cdli_provenience_id_P694',
       'transciption_name', 'language', 'tr_name', 'ara_name_x', 'arm_name_x',
       'fas_name_x', 'geo_name_x', 'gre_name_x', 'heb_name_x', 'rus_name_x',
       'pleiades_id_P671', 'osm_id', 'osm_type', 'site_id_x', 'geonames_id',
       'Unnamed: 47', 'wik_ara_x', 'wik_fas_x', 'wik_gre_x', 'wik_heb_x',
       'wik_en.1', 'lan', 'qid.2',
       'qid,Len,Lfr,Lde,Den,P2,P2,P131,P131,P48,P670,qal18', 'place', 'link',
       'placeLabel', 'site_id_y', 'cdli_provenience_id', 'accuracy_y',
       'anc_name_y', 'transc_name', 'ara_name_y', 'arm_name_y', 'fas_name_y',
       'geo_name_y', 'gre_name_y', 'heb_name_y', 'rus_name_y', 'legacy_name',
       'pleiades_url', 'osm_url', 'geonames_url', 'wik_en_y', 'wik_ara_y',
       'wik_fas_y', 'wik_gre_y', 'wik_heb_y', 'wik_tr_y', 'rla_url',
       'wikidata_url', 'lon_wgs1984_y', 'lat_wgs1984_y', 'geometry', '_merge'],
      dtype='object')

In [ ]:
CIGS_MERGE_old = CIGS_FG_without_quote.merge(CIGS_old, how = 'right', left_on = 'transciption_name', right_on = "transc_name",indicator= True)
CIGS_MERGE_old.columns

Index(['Unnamed: 0', 'Double record?', 'qid', 'Sarwiki', 'P418', 'P34',
       'Unnamed: 5', 'Unnamed: 6', 'Senwiki', 'P671', 'P34.1', 'Wikidata_qid',
       'Wikidata2', 'Len', 'Den', 'P2', 'P2.1', 'P131', 'P131.1',
       'lat_lon_P48', 'P670', 'qal18', 'wik_en_x', 'sv.wiki', 'wik_tr_x',
       'Description', 'anc_name_x', 'lat_wgs1984', 'lon_wgs1984', 'accuracy_x',
       'qid.1', 'cdli_legacy_"Len"', 'cdli_provenience_id_P694',
       'transciption_name', 'language', 'tr_name', 'ara_name_x', 'arm_name_x',
       'fas_name_x', 'geo_name_x', 'gre_name_x', 'heb_name_x', 'rus_name_x',
       'pleiades_id_P671', 'osm_id_x', 'osm_type_x', 'site_id_x',
       'geonames_id_x', 'Unnamed: 47', 'wik_ara_x', 'wik_fas_x', 'wik_gre_x',
       'wik_heb_x', 'wik_en.1', 'lan', 'qid.2',
       'qid,Len,Lfr,Lde,Den,P2,P2,P131,P131,P48,P670,qal18', 'place', 'link',
       'placeLabel', 'site_id_y', 'cdli_provenience_id', 'accuracy_y',
       'anc_name_y', 'transc_name', 'ara_name_y', 'arm_name_y', 'fas_name_y',
       'geo_name_y', 'gre_name_y', 'heb_name_y', 'rus_name_y', 'pleiades_id',
       'osm_id_y', 'osm_type_y', 'geonames_id_y', 'cdli_legacy', 'wik_en_y',
       'wik_ara_y', 'wik_fas_y', 'wik_gre_y', 'wik_heb_y', 'wik_tr_y',
       'geometry', '_merge'],
      dtype='object')

In [ ]:
CIGS_MERGE.to_csv('/content/drive/MyDrive/FactGrid Cuneiform (AWCA)/geography/CIGS_FG_loss_v6.csv')

In [ ]:
CIGS_FG_loss = CIGS_MERGE.loc[CIGS_MERGE['_merge'] == 'right_only']

CIGS_FG_loss

,Unnamed: 0,Double record?,qid,Sarwiki,P418,P34,Unnamed: 5,Unnamed: 6,Senwiki,P671,...,wik_fas_y,wik_gre_y,wik_heb_y,wik_tr_y,rla_url,wikidata_url,lon_wgs1984_y,lat_wgs1984_y,geometry,_merge
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,46.6926,30.7382,None,right_only
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,https://tr.wikipedia.org/wiki/Adilcevaz,,https://wikidata.org/wiki/Q357251,42.7291,38.8014,None,right_only
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,45.0956,32.5741,None,right_only
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,https://wikidata.org/wiki/Q7697374,36.7988,35.9039,None,right_only
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,44.8225,32.4605,None,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,45.0983,32.5612,None,right_only
561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,https://wikidata.org/wiki/Q27365,38.5499,27.6219,None,right_only
565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,46.5784,31.3901,None,right_only
584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,45.3421,32.1834,None,right_only
595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,,,,,,,,None,right_only

In [ ]:
booleen = CIGS_MERGE.columns.isin(CIGS_MERGE_old.columns)
new_col = CIGS_MERGE.columns.to_series()
new_col.loc[booleen != True]

lat_wgs1984_x    lat_wgs1984_x
lon_wgs1984_x    lon_wgs1984_x
osm_id                  osm_id
osm_type              osm_type
geonames_id        geonames_id
legacy_name        legacy_name
pleiades_url      pleiades_url
osm_url                osm_url
geonames_url      geonames_url
rla_url                rla_url
wikidata_url      wikidata_url
lon_wgs1984_y    lon_wgs1984_y
lat_wgs1984_y    lat_wgs1984_y
dtype: object

In [ ]:
# CIGS_FG_loss.to_csv('/content/drive/MyDrive/FactGrid Cuneiform (AWCA)/geography/CIGS_FG_loss.csv')

In [ ]:
factgrid = pd.read_json('/content/drive/MyDrive/FactGrid Cuneiform (AWCA)/geography/query.json')
factgrid

,ancientplace,coord,romanscript,namehistory,cdli2,pleiades
0,https://database.factgrid.de/entity/Q389901,Point(43.2304 35.5931),Tall Ḥuwaysh,تل حويش,95.0,NaN
1,https://database.factgrid.de/entity/Q389900,Point(41.166 36.816),Tall Ḥamīdī,تل حميدي,NaN,874740.0
2,https://database.factgrid.de/entity/Q389898,Point(40.0399 36.8268),Tall Ḥalaf,تل حلف,NaN,874739.0
3,https://database.factgrid.de/entity/Q389892,Point(45.7032 31.8254),Tall Jidar,تل جدر,318.0,912957.0
4,https://database.factgrid.de/entity/Q389891,Point(40.5872 36.7381),Tall Baiydar,تل بيدر,260.0,423885388.0
...,...,...,...,...,...,...
581,https://database.factgrid.de/entity/Q390009,Point(45.1764 35.5579),Kānī Shāyah,كاني شاية,NaN,NaN
582,https://database.factgrid.de/entity/Q390019,Point(43.4762 36.0446),Nigūb,نگوب,273.0,413309737.0
583,https://database.factgrid.de/entity/Q390073,Point(40.7929 37.7936),Ziyaret Tepe,NaN,244.0,NaN
584,https://database.factgrid.de/entity/Q390044,Point(36.9096 39.3084),Kuşaklı,NaN,190.0,117143016.0
585,https://database.factgrid.de/entity/Q390020,Point(43.3385 36.1022),Nimrūd,نمرود,81.0,894019.0

In [ ]:
CIGS_MERGE = CIGS_MERGE.drop("_merge", axis = 1)
factgrid_merge = factgrid.merge(CIGS_MERGE, how = 'left', left_on = 'romanscript', right_on = 'transc_name', indicator= True)
factgrid_merge

,ancientplace,coord,romanscript,namehistory,cdli2,pleiades,Unnamed: 0,Double record?,qid,Sarwiki,...,wik_fas_y,wik_gre_y,wik_heb_y,wik_tr_y,rla_url,wikidata_url,lon_wgs1984_y,lat_wgs1984_y,geometry,_merge
0,https://database.factgrid.de/entity/Q389901,Point(43.2304 35.5931),Tall Ḥuwaysh,تل حويش,95.0,NaN,58.0,NaN,Q389901,NaN,...,,,,,,,43.2304,35.5931,None,both
1,https://database.factgrid.de/entity/Q389900,Point(41.166 36.816),Tall Ḥamīdī,تل حميدي,NaN,874740.0,303.0,NaN,Q389900,NaN,...,,,,,,,41.1660,36.8160,None,both
2,https://database.factgrid.de/entity/Q389898,Point(40.0399 36.8268),Tall Ḥalaf,تل حلف,NaN,874739.0,289.0,NaN,Q389898,NaN,...,,,,,,,40.0399,36.8268,None,both
3,https://database.factgrid.de/entity/Q389892,Point(45.7032 31.8254),Tall Jidar,تل جدر,318.0,912957.0,195.0,NaN,Q389892,NaN,...,,,,,,,45.7032,31.8254,None,both
4,https://database.factgrid.de/entity/Q389891,Point(40.5872 36.7381),Tall Baiydar,تل بيدر,260.0,423885388.0,155.0,NaN,Q389891,تل_بيدر,...,,,,,,https://wikidata.org/wiki/Q1658146,40.5872,36.7381,None,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
603,https://database.factgrid.de/entity/Q390009,Point(45.1764 35.5579),Kānī Shāyah,كاني شاية,NaN,NaN,486.0,NaN,Q390009,NaN,...,,,,,,,45.1764,35.5579,None,both
604,https://database.factgrid.de/entity/Q390019,Point(43.4762 36.0446),Nigūb,نگوب,273.0,413309737.0,164.0,NaN,Q390019,NaN,...,,,,,,,43.4762,36.0446,None,both
605,https://database.factgrid.de/entity/Q390073,Point(40.7929 37.7936),Ziyaret Tepe,NaN,244.0,NaN,143.0,NaN,Q390073,NaN,...,,,,https://tr.wikipedia.org/wiki/Ziyaret_Tepe_Höyüğü,,https://wikidata.org/wiki/Q4819172,40.7929,37.7936,None,both
606,https://database.factgrid.de/entity/Q390044,Point(36.9096 39.3084),Kuşaklı,NaN,190.0,117143016.0,115.0,NaN,Q390044,NaN,...,,,,https://tr.wikipedia.org/wiki/Sarissa,,,36.9096,39.3084,None,both
607,https://database.factgrid.de/entity/Q390020,Point(43.3385 36.1022),Nimrūd,نمرود,81.0,894019.0,268.0,NaN,Q390020,كالح,...,,,,,,https://wikidata.org/wiki/Q237614,43.3385,36.1022,None,both

In [3]:
# factgrid_merge["P402_(Wikidata)"] = factgrid_merge['osm_id_x']
# factgrid_merge["P10689_(Wikidata)"] = factgrid_merge["osm_type_x"]

In [ ]:
# factgrid_merge = factgrid_merge.drop("romanscript", axis =1 )

In [2]:
# factgrid_merge.columns

In [ ]:
# factgrid_merge.to_csv('/content/drive/MyDrive/FactGrid Cuneiform (AWCA)/geography/factgrid_merge.csv')

In [1]:
# id_columns = factgrid_merge[['qid','P402_(Wikidata)', 'P10689_(Wikidata)']]
# id_columns

In [ ]:
# id_columns.to_csv('/content/drive/MyDrive/FactGrid Cuneiform (AWCA)/geography/id_columns.csv')

In [ ]:
# factgrid_loss = factgrid_merge.loc[factgrid_merge['_merge'] == 'left_only']
# factgrid_loss

In [ ]:
# factgrid_loss.to_csv('/content/drive/MyDrive/FactGrid Cuneiform (AWCA)/geography/factgrid_loss.csv')

In [ ]:
# factgrid_merge.to_csv('/content/drive/MyDrive/FactGrid Cuneiform (AWCA)/geography/factgrid_merge.csv')

Next steps (10-26-22):

i. *Check / match with this dataset:* https://docs.google.com/spreadsheets/d/1P9OQSvQ18EkFg2AiI9QZpF5eQbvahy2wOZQqzKvOorI/edit?usp=sharing

ii. *link `cdli_legacy` (wtih `romanscript` `ancientplace`)  to Chronology:*